### PR TITLE
Add setMaxRows to IOperation

### PR DESCRIPTION
**Pull request by drzippie**
Need to use method operation.setMaxRows( number )

Issue: #41

### CODE REVIEW

**Review by lenchv — APPROVED** [review]

**Comment by drzippie** [comment]
The test "HiveClient.connect" > should use tcp connection by default:  Fails in the current master branch:

```
     TypeError [ERR_MISSING_ARGS]: The "options" or "port" or "path" argument must be specified
```

I've fixed the test setting port and path to validate that client.connectionProvider is a instance of TcpConnection

**Comment by lenchv** [comment]
Hi @drzippie ! Looks fine, the wierd thing that test failed, but seems to be correct. I'll merge and release changes soon. Cheers =)

**Comment by drzippie** [comment]
@lenchv  ... sorry, seems to be needed execute a npm run build, and commit `dist/contracts/IOperation.d.ts`

I had erroneously assumed that `dist` was generated automatically

**Comment by lenchvolodymyr** [comment]
whoops, I also forget about this. I'll build and release it, no worries

**Comment by lenchv** [comment]
whoops, I also forget about this. I'll build and release it, no worries

**Pull request merged**
